-   id: pkgcheck
    name: pkgcheck
    description: ''
    entry: pkgcheck
    language: python
    'files': \.ebuild$
    args: ["scan", "--cache=no", "--color=no"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
