name: main
on:
  push:
    branches: [master]
  schedule:
  - cron: '40 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name 'Github Action'
    - run: git config --global user.email 'action@github.com'
    - run: pre-commit-mirror . --language=python --package-name=pkgcheck --files-regex='\.ebuild$' --args='scan,--cache=no,--color=no'
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/master --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
